server:
  applicationConnectors:
  - type: http
    port: 50051
  adminConnectors:
  - type: http
    port: 50151

printingPort: 50052
packagingPort: 50053

printingHost: "localhost"
packagingHost: "localhost"
